- name: Deploy Web Page and Web Server
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed

  - name: Start httpd
    service:
      name: httpd
      state: started

  - name: Copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html

